var searchData=
[
  ['carp_0',['CArp',['../classCArp.html',1,'']]],
  ['category_1',['category',['../classCParameterOperate.html#section_CParameterOperate_CATEGORY_USAGE',1,'CParameterOperate category'],['../classCParameter.html#sub_CParameter_CATEGORY_USAGE',1,'Parameter category']]],
  ['cb_5fpost_5fconnect_2',['cb_post_connect',['../classCBackendFreeRDP.html#aeadca916625ea415fd41a43a8afea525',1,'CBackendFreeRDP']]],
  ['cb_5fpre_5fconnect_3',['cb_pre_connect',['../classCBackendFreeRDP.html#a43803903b09b2c90d6c5f524b3d3a6b0',1,'CBackendFreeRDP']]],
  ['cb_5fverify_5fcertificate_5fex_4',['cb_verify_certificate_ex',['../classCBackendFreeRDP.html#a306af3031941a6f02e602d7a5c7d66c5',1,'CBackendFreeRDP']]],
  ['cb_5fverify_5fchanged_5fcertificate_5fex_5',['cb_verify_changed_certificate_ex',['../classCBackendFreeRDP.html#af12cea42be0c208dfec240bbe03fc481',1,'CBackendFreeRDP']]],
  ['cb_5fverify_5fx509_5fcertificate_6',['cb_verify_x509_certificate',['../classCBackendFreeRDP.html#a823c71599d563dc965c0b1e26b681a57',1,'CBackendFreeRDP']]],
  ['cbackend_7',['CBackend',['../classCBackend.html',1,'']]],
  ['cbackenddesktop_8',['CBackendDesktop',['../classCBackendDesktop.html',1,'']]],
  ['cbackendfiletransfer_9',['CBackendFileTransfer',['../classCBackendFileTransfer.html',1,'']]],
  ['cbackendfreerdp_10',['CBackendFreeRDP',['../classCBackendFreeRDP.html',1,'']]],
  ['cbackendlibvncserver_11',['CBackendLibVNCServer',['../classCBackendLibVNCServer.html',1,'']]],
  ['cbackendplayer_12',['CBackendPlayer',['../classCBackendPlayer.html',1,'']]],
  ['cbackendssh_13',['CBackendSSH',['../classCBackendSSH.html',1,'']]],
  ['cbackendthread_14',['CBackendThread',['../classCBackendThread.html',1,'']]],
  ['cbackendvnc_15',['CBackendVnc',['../classCBackendVnc.html',1,'']]],
  ['cchannel_16',['cchannel',['../classCChannel.html',1,'CChannel'],['../classCChannel.html#af80ab8220269cccf1cd9fd5fb74271cc',1,'CChannel::CChannel()']]],
  ['cchannelice_17',['CChannelIce',['../classCChannelIce.html',1,'']]],
  ['cchannelsftp_18',['CChannelSFTP',['../classCChannelSFTP.html',1,'']]],
  ['cchannelssh_19',['CChannelSSH',['../classCChannelSSH.html',1,'']]],
  ['cchannelsshterminal_20',['CChannelSSHTerminal',['../classCChannelSSHTerminal.html',1,'']]],
  ['cchannelsshtunnel_21',['CChannelSSHTunnel',['../classCChannelSSHTunnel.html',1,'']]],
  ['cchannelsshtunnelforward_22',['CChannelSSHTunnelForward',['../classCChannelSSHTunnelForward.html',1,'']]],
  ['cclipboardfreerdp_23',['CClipboardFreeRDP',['../classCClipboardFreeRDP.html',1,'']]],
  ['cclipboardmimedata_24',['CClipboardMimeData',['../classCClipboardMimeData.html',1,'']]],
  ['cconnection_25',['CConnection',['../classCConnection.html',1,'']]],
  ['cconnectlayer_26',['CConnectLayer',['../classCConnectLayer.html',1,'']]],
  ['cconnectlayerqtcpsocket_27',['CConnectLayerQTcpSocket',['../classCConnectLayerQTcpSocket.html',1,'']]],
  ['cconvertkeycode_28',['CConvertKeyCode',['../classCConvertKeyCode.html',1,'']]],
  ['ccursorfreerdp_29',['CCursorFreeRDP',['../classCCursorFreeRDP.html',1,'']]],
  ['cdesktop_30',['CDesktop',['../classCDesktop.html',1,'']]],
  ['cdesktopwindows_31',['CDesktopWindows',['../classCDesktopWindows.html',1,'']]],
  ['cdesktopxlib_32',['CDesktopXLib',['../classCDesktopXLib.html',1,'']]],
  ['cdisplay_33',['CDisplay',['../classCDisplay.html',1,'']]],
  ['cdisplaywindows_34',['CDisplayWindows',['../classCDisplayWindows.html',1,'']]],
  ['cdisplayxlib_35',['CDisplayXLib',['../classCDisplayXLib.html',1,'']]],
  ['cdlgcapture_36',['CDlgCapture',['../classCDlgCapture.html',1,'']]],
  ['cdlgdesktopsize_37',['CDlgDesktopSize',['../classCDlgDesktopSize.html',1,'']]],
  ['cdlgfiletransfer_38',['CDlgFileTransfer',['../classCDlgFileTransfer.html',1,'']]],
  ['cdlggetuserpasswordfreerdp_39',['CDlgGetUserPasswordFreeRDP',['../classCDlgGetUserPasswordFreeRDP.html',1,'']]],
  ['cdlginputpassword_40',['CDlgInputPassword',['../classCDlgInputPassword.html',1,'']]],
  ['cdlgplayer_41',['CDlgPlayer',['../classCDlgPlayer.html',1,'']]],
  ['cdlgsetfreerdp_42',['CDlgSetFreeRDP',['../classCDlgSetFreeRDP.html',1,'']]],
  ['cdlgsettingslibvnc_43',['CDlgSettingsLibVnc',['../classCDlgSettingsLibVnc.html',1,'']]],
  ['cdlgsettingsrawstream_44',['CDlgSettingsRawStream',['../classCDlgSettingsRawStream.html',1,'']]],
  ['cdlgsettingsserialport_45',['CDlgSettingsSerialPort',['../classCDlgSettingsSerialPort.html',1,'']]],
  ['cdlgsettingsssh_46',['CDlgSettingsSSH',['../classCDlgSettingsSSH.html',1,'']]],
  ['cdlgsettingstelnet_47',['CDlgSettingsTelnet',['../classCDlgSettingsTelnet.html',1,'']]],
  ['cdlgsettingsterminal_48',['CDlgSettingsTerminal',['../classCDlgSettingsTerminal.html',1,'']]],
  ['cdlgsettingsvnc_49',['CDlgSettingsVnc',['../classCDlgSettingsVnc.html',1,'']]],
  ['cdlguserpassword_50',['CDlgUserPassword',['../classCDlgUserPassword.html',1,'']]],
  ['cevent_51',['CEvent',['../classChannel_1_1CEvent.html',1,'Channel']]],
  ['cfavoritemimedata_52',['CFavoriteMimeData',['../classCFavoriteMimeData.html',1,'']]],
  ['cfavoriteview_53',['CFavoriteView',['../classCFavoriteView.html',1,'']]],
  ['cfiletransfer_54',['CFileTransfer',['../classCFileTransfer.html',1,'']]],
  ['cframepixelbuffer_55',['CFramePixelBuffer',['../classCFramePixelBuffer.html',1,'']]],
  ['cfrmactive_56',['CFrmActive',['../classCFrmActive.html',1,'']]],
  ['cfrmfiletransfer_57',['CFrmFileTransfer',['../classCFrmFileTransfer.html',1,'']]],
  ['cfrmfullscreentoolbar_58',['CFrmFullScreenToolBar',['../classCFrmFullScreenToolBar.html',1,'']]],
  ['cfrmlistrecent_59',['CFrmListRecent',['../classCFrmListRecent.html',1,'']]],
  ['cfrmparameterfreerdp_60',['CFrmParameterFreeRDP',['../classCFrmParameterFreeRDP.html',1,'']]],
  ['cfrmparameterice_61',['cfrmparameterice',['../classCFrmParameterICE.html#ac55c5b68fa1dd5a55ada50867971ee5c',1,'CFrmParameterICE::CFrmParameterICE()'],['../classCFrmParameterICE.html',1,'CFrmParameterICE']]],
  ['cfrmparameterrabbitvnc_62',['CFrmParameterRabbitVNC',['../classCFrmParameterRabbitVNC.html',1,'']]],
  ['cfrmparameterservicelibvnc_63',['CFrmParameterServiceLibVNC',['../classCFrmParameterServiceLibVNC.html',1,'']]],
  ['cfrmparametertigervnc_64',['CFrmParameterTigerVNC',['../classCFrmParameterTigerVNC.html',1,'']]],
  ['cfrmplayer_65',['CFrmPlayer',['../classCFrmPlayer.html',1,'']]],
  ['cfrmscroll_66',['CFrmScroll',['../classCFrmScroll.html',1,'']]],
  ['cfrmviewer_67',['CFrmViewer',['../classCFrmViewer.html',1,'']]],
  ['cfrmvieweropengl_68',['CFrmViewerOpenGL',['../classCFrmViewerOpenGL.html',1,'']]],
  ['cfrmwakeonlan_69',['CFrmWakeOnLan',['../classCFrmWakeOnLan.html',1,'']]],
  ['change_20log_70',['Change Log',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2ChangeLog.html',1,'']]],
  ['channel_71',['Channel',['../group__LIBAPI__CHANNEL.html',1,'']]],
  ['checkvalidity_72',['checkvalidity',['../classCParameter.html#a5744cebce5aa518a7d1d086b05001943',1,'CParameter::CheckValidity()'],['../classCParameterUI.html#a065a08e831af33efb0f85b0b368965ba',1,'CParameterUI::CheckValidity()'],['../classCParameterSSHTunnelUI.html#a33669dd1c4cceb879f433826f25e875e',1,'CParameterSSHTunnelUI::CheckValidity()'],['../classCParameterProxyUI.html#a7a24c358ced79bdf2a93d90901b66803',1,'CParameterProxyUI::CheckValidity()'],['../classCParameterNetUI.html#a2e3de7d23619855cdcc4746d31a503c9',1,'CParameterNetUI::CheckValidity()']]],
  ['chook_73',['CHook',['../classCHook.html',1,'']]],
  ['chookunix_74',['CHookUnix',['../classCHookUnix.html',1,'']]],
  ['chookwindows_75',['CHookWindows',['../classCHookWindows.html',1,'']]],
  ['cice_76',['cice',['../classCICE.html#a8431f62fd24b65defaef75cd21e30b9a',1,'CICE::CICE()'],['../classCICE.html',1,'CICE']]],
  ['cicesignal_77',['cicesignal',['../classCIceSignal.html#a6a8ca647d5db218b6b3b72d3085440da',1,'CIceSignal::CIceSignal()'],['../classCIceSignal.html',1,'CIceSignal']]],
  ['cicesignalqxmpp_78',['CIceSignalQxmpp',['../classCIceSignalQxmpp.html',1,'']]],
  ['cicesignalqxmppiq_79',['cicesignalqxmppiq',['../classCIceSignalQXmppIq.html#af77730e27c910a874ec1353260c8ff36',1,'CIceSignalQXmppIq::CIceSignalQXmppIq()'],['../classCIceSignalQXmppIq.html',1,'CIceSignalQXmppIq']]],
  ['cicesignalqxmppmanager_80',['cicesignalqxmppmanager',['../classCIceSignalQXmppManager.html#ae25270385ff345d555c1f7e2bda4fd1f',1,'CIceSignalQXmppManager::CIceSignalQXmppManager()'],['../classCIceSignalQXmppManager.html',1,'CIceSignalQXmppManager']]],
  ['cicesignalwebsocket_81',['cicesignalwebsocket',['../classCIceSignalWebSocket.html',1,'CIceSignalWebSocket'],['../classCIceSignalWebSocket.html#a5e3cef4598571a556a3425f98be36eb0',1,'CIceSignalWebSocket::CIceSignalWebSocket()']]],
  ['cinputdevice_82',['CInputDevice',['../classCInputDevice.html',1,'']]],
  ['cinputdevicewindows_83',['CInputDeviceWindows',['../classCInputDeviceWindows.html',1,'']]],
  ['cinputdevicexlib_84',['CInputDeviceXLib',['../classCInputDeviceXLib.html',1,'']]],
  ['cinstreamchannel_85',['CInStreamChannel',['../classCInStreamChannel.html',1,'']]],
  ['class_86',['class',['../group__gOperateDesktop.html',1,'Desktop class'],['../group__gOperateTerminal.html',1,'Terminal class']]],
  ['clean_87',['clean',['../classCOperateDesktop.html#ae045badc0648d4beef1df5fb5f9bf7ac',1,'COperateDesktop::Clean()'],['../classCOperateTerminal.html#a6cba137ee33e02e4ee1a8e77466e4449',1,'COperateTerminal::Clean()'],['../classCScreenCapture.html#ae9b654724e5db773c451315f7236fd01',1,'CScreenCapture::Clean()'],['../classCOperatePlayer.html#a0c0c23a84e5eb7d63315c776539e8122',1,'COperatePlayer::Clean()'],['../classCOperateLibVNCServer.html#a4606f87c3277cfc7a5ea83800d8eb294',1,'COperateLibVNCServer::Clean()'],['../classCOperateFreeRDP.html#ac5c1cb00afd933e39d479d10d401b43f',1,'COperateFreeRDP::Clean()'],['../classCOperateFileTransfer.html#a6ce0ad393a2e521b222dbcbd40625450',1,'COperateFileTransfer::Clean()'],['../classCOperate.html#a8346829a47ba836dcc06746cc8444929',1,'COperate::Clean()'],['../classCOperateWakeOnLan.html#a27f15827fbe3852fd34c4d897b0fa84f',1,'COperateWakeOnLan::Clean()'],['../classCOperateVnc.html#ab4a5f9e21eb49b45c12529366e597bb5',1,'COperateVnc::Clean()'],['../classCOperateSSH.html#a0c044d9b0658a65cca394a24b1f17978',1,'COperateSSH::Clean()']]],
  ['clibdatachannellogcallback_88',['CLibDataChannelLogCallback',['../classCLibDataChannelLogCallback.html',1,'']]],
  ['client_89',['client',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2Plugins_2TigerVnc_2README.html#autotoc_md278',1,'Client'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2Plugins_2RabbitVNC_2README.html#autotoc_md268',1,'Client'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2Plugins_2LibVNCServer_2README.html#autotoc_md254',1,'Client'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2Plugins_2FreeRDP_2README.html#autotoc_md244',1,'Client']]],
  ['client_20resource_20image_20app_20png_20width_2048_20height_2048_20a_20href_20https_3a_20github_20com_20kanglin_20rabbitremotecontrol_20玉兔远程控制_20a_90',['&lt;img src=&quot;App/Client/Resource/Image/app.png&quot; width=&quot;48&quot; height=&quot;48&quot; /&gt;&lt;a href=&quot;https://github.com/KangLin/RabbitRemoteControl&quot; &gt;玉兔远程控制&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README__zh__CN.html',1,'']]],
  ['client_20resource_20image_20app_20png_20width_2048_20height_2048_20a_20href_20https_3a_20github_20com_20kanglin_20rabbitremotecontrol_20rabbit_20remote_20control_20a_91',['&lt;img src=&quot;App/Client/Resource/Image/app.png&quot; width=&quot;48&quot; height=&quot;48&quot; /&gt;&lt;a href=&quot;https://github.com/KangLin/RabbitRemoteControl&quot; &gt;Rabbit Remote Control&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README.html',1,'']]],
  ['clientcontext_92',['ClientContext',['../structCBackendFreeRDP_1_1ClientContext.html',1,'CBackendFreeRDP']]],
  ['clistfilemodel_93',['CListFileModel',['../classCListFileModel.html',1,'']]],
  ['cmainwindow_94',['CMainWindow',['../classCMainWindow.html',1,'']]],
  ['cmake_20参数或者环境变量_95',['CMake 参数或者环境变量',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md162',1,'']]],
  ['cmake_20支持不够。_96',['[可选] IDE: Qt Creator。建议使用 v5.0.2 及以后版本，以前版本对 CMake 支持不够。',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md144',1,'']]],
  ['cmake_20org_20http_3a_20www_20cmake_20org_20a_97',['CMAKE: &lt;a href=&quot;http://www.cmake.org&quot; &gt;http://www.cmake.org&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md141',1,'']]],
  ['cmake_20org_20https_3a_20cmake_20org_20a_98',['CMake: &lt;a href=&quot;https://cmake.org/&quot; &gt;https://cmake.org&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md103',1,'']]],
  ['cmake_20parameters_20or_20environment_20variable_99',['CMake parameters or environment variable',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md124',1,'']]],
  ['cmake_3a_20a_20href_20http_3a_20www_20cmake_20org_20http_3a_20www_20cmake_20org_20a_100',['CMAKE: &lt;a href=&quot;http://www.cmake.org&quot; &gt;http://www.cmake.org&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md141',1,'']]],
  ['cmake_3a_20a_20href_20https_3a_20cmake_20org_20https_3a_20cmake_20org_20a_101',['CMake: &lt;a href=&quot;https://cmake.org/&quot; &gt;https://cmake.org&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md103',1,'']]],
  ['cmanageconnect_102',['CManageConnect',['../classCManageConnect.html',1,'']]],
  ['cmanageplugins_103',['CManagePlugins',['../classCManagePlugins.html',1,'']]],
  ['cmanager_104',['CManager',['../classCManager.html',1,'']]],
  ['cnativeeventfilterunix_105',['CNativeEventFilterUnix',['../classCNativeEventFilterUnix.html',1,'']]],
  ['code_106',['Source code',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md123',1,'']]],
  ['com_20http_3a_20www_20git_20scm_20com_20a_107',['GIT: &lt;a href=&quot;http://www.git-scm.com&quot; &gt;http://www.git-scm.com&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md140',1,'']]],
  ['com_20https_3a_20www_20git_20scm_20com_20a_108',['Git: &lt;a href=&quot;https://www.git-scm.com/&quot; &gt;https://www.git-scm.com&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md102',1,'']]],
  ['com_20kanglin_20rabbitremotecontrol_20玉兔远程控制_20a_109',['&lt;img src=&quot;App/Client/Resource/Image/app.png&quot; width=&quot;48&quot; height=&quot;48&quot; /&gt;&lt;a href=&quot;https://github.com/KangLin/RabbitRemoteControl&quot; &gt;玉兔远程控制&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README__zh__CN.html',1,'']]],
  ['com_20kanglin_20rabbitremotecontrol_20rabbit_20remote_20control_20a_110',['&lt;img src=&quot;App/Client/Resource/Image/app.png&quot; width=&quot;48&quot; height=&quot;48&quot; /&gt;&lt;a href=&quot;https://github.com/KangLin/RabbitRemoteControl&quot; &gt;Rabbit Remote Control&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README.html',1,'']]],
  ['com_20linuxdeploy_20linuxdeploy_20appimage_20a_111',['com linuxdeploy linuxdeploy appimage a',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md129',1,'&lt;a href=&quot;https://github.com/linuxdeploy/linuxdeploy&quot; &gt;AppImage&lt;/a&gt;'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md167',1,'&lt;a href=&quot;https://github.com/linuxdeploy/linuxdeploy&quot; &gt;AppImage&lt;/a&gt;']]],
  ['compilation_112',['compilation',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md125',1,'Compilation'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Windows.html#autotoc_md177',1,'Compilation'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README.html#autotoc_md313',1,'Compilation']]],
  ['compilation_20example_113',['Compilation example',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md127',1,'']]],
  ['compile_114',['Compile',['../index.html#autotoc_md218',1,'']]],
  ['compile_20this_20project_115',['compile this project',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Windows.html#autotoc_md190',1,'Compile this project'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md122',1,'Compile this project']]],
  ['compiling_20for_20linux_116',['Compiling for Linux',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html',1,'']]],
  ['compiling_20for_20windows_117',['Compiling for Windows',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Windows.html',1,'']]],
  ['compone_118',['Parameter compone',['../group__CLIENT__PARAMETER__COMPONE.html',1,'']]],
  ['concern_119',['Other points of concern',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2Package_2Flatpak_2shared-modules_2vorbisgain_2README.html#autotoc_md239',1,'']]],
  ['configure_20programe_120',['Rabbit remote control service configure programe',['../group__ServiceConfigure.html',1,'']]],
  ['connecter_20parameter_121',['Use connecter parameter',['../classCParameterBase.html#section_Use_CParameterBase',1,'']]],
  ['connectlayersshtunnel_122',['ConnectLayerSSHTunnel',['../classConnectLayerSSHTunnel.html',1,'']]],
  ['console_123',['A: This is because there is no desktop environment set up to run the program from the console.',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Wiki_2Wiki.html#autotoc_md234',1,'']]],
  ['contribution_124',['Contribution',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README.html#autotoc_md309',1,'']]],
  ['contributors_125',['Contributors',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2Authors.html#autotoc_md1',1,'']]],
  ['control_20a_126',['&lt;img src=&quot;App/Client/Resource/Image/app.png&quot; width=&quot;48&quot; height=&quot;48&quot; /&gt;&lt;a href=&quot;https://github.com/KangLin/RabbitRemoteControl&quot; &gt;Rabbit Remote Control&lt;/a&gt;',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README.html',1,'']]],
  ['control_20development_20document_127',['Rabbit Remote Control Development Document',['../index.html',1,'']]],
  ['control_20programe_128',['Rabbit remote control programe',['../group__VIEWER__APP.html',1,'']]],
  ['control_20protocols_129',['Remote control protocols',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2README.html#autotoc_md301',1,'']]],
  ['control_20service_20configure_20programe_130',['Rabbit remote control service configure programe',['../group__ServiceConfigure.html',1,'']]],
  ['control_20service_20programe_131',['Rabbit remote control service programe',['../group__Service.html',1,'']]],
  ['copenglinit_132',['COpenGLInit',['../classCOpenGLInit.html',1,'']]],
  ['coperate_133',['COperate',['../classCOperate.html',1,'']]],
  ['coperatedesktop_134',['coperatedesktop',['../classCOperateDesktop.html#a50c58f04821423cff60fdc6dd7c0d3aa',1,'COperateDesktop::COperateDesktop()'],['../classCOperateDesktop.html',1,'COperateDesktop']]],
  ['coperatefiletransfer_135',['COperateFileTransfer',['../classCOperateFileTransfer.html',1,'']]],
  ['coperatefreerdp_136',['COperateFreeRDP',['../classCOperateFreeRDP.html',1,'']]],
  ['coperatelibvncserver_137',['COperateLibVNCServer',['../classCOperateLibVNCServer.html',1,'']]],
  ['coperateplayer_138',['COperatePlayer',['../classCOperatePlayer.html',1,'']]],
  ['coperaterawstream_139',['COperateRawStream',['../classCOperateRawStream.html',1,'']]],
  ['coperateserialport_140',['COperateSerialPort',['../classCOperateSerialPort.html',1,'']]],
  ['coperatessh_141',['COperateSSH',['../classCOperateSSH.html',1,'']]],
  ['coperatetelnet_142',['COperateTelnet',['../classCOperateTelnet.html',1,'']]],
  ['coperateterminal_143',['COperateTerminal',['../classCOperateTerminal.html',1,'']]],
  ['coperatevnc_144',['COperateVnc',['../classCOperateVnc.html',1,'']]],
  ['coperatewakeonlan_145',['COperateWakeOnLan',['../classCOperateWakeOnLan.html',1,'']]],
  ['coutstreamchannel_146',['COutStreamChannel',['../classCOutStreamChannel.html',1,'']]],
  ['cparameter_147',['cparameter',['../classCParameter.html#af01ed678eb8a06464823ded27b39c734',1,'CParameter::CParameter()'],['../classCParameter.html',1,'CParameter']]],
  ['cparameter_20interface_20functions_148',['CParameter Interface functions',['../classCParameter.html#CParameter_Functions',1,'']]],
  ['cparameterapp_149',['CParameterApp',['../classCParameterApp.html',1,'']]],
  ['cparameterbase_150',['CParameterBase',['../classCParameterBase.html',1,'']]],
  ['cparameterdlgsettings_151',['CParameterDlgSettings',['../classCParameterDlgSettings.html',1,'']]],
  ['cparameterfiletransfer_152',['CParameterFileTransfer',['../classCParameterFileTransfer.html',1,'']]],
  ['cparameterfreerdp_153',['CParameterFreeRDP',['../classCParameterFreeRDP.html',1,'']]],
  ['cparameterice_154',['CParameterICE',['../classCParameterICE.html',1,'']]],
  ['cparameterlibvncserver_155',['CParameterLibVNCServer',['../classCParameterLibVNCServer.html',1,'']]],
  ['cparameternet_156',['cparameternet',['../classCParameterNet.html',1,'CParameterNet'],['../classCParameterNet.html#a5f3710a55f44c47e3af64492d4ce235b',1,'CParameterNet::CParameterNet()']]],
  ['cparameternetui_157',['CParameterNetUI',['../classCParameterNetUI.html',1,'']]],
  ['cparameteroperate_158',['cparameteroperate',['../classCParameterOperate.html',1,'CParameterOperate'],['../classCParameterOperate.html#sub_Set_CParameterPlugin_in_CParameterOperate',1,'Set CParameterPlugin for CParameterOperate'],['../classCParameterOperate.html#sub_Use_CParameterPlugin_in_CParameterOperate',1,'Use CParameterPlugin in CParameterOperate']]],
  ['cparameteroperate_20category_159',['CParameterOperate category',['../classCParameterOperate.html#section_CParameterOperate_CATEGORY_USAGE',1,'']]],
  ['cparameterplayer_160',['CParameterPlayer',['../classCParameterPlayer.html',1,'']]],
  ['cparameterplugin_161',['cparameterplugin',['../classCParameterPlugin.html',1,'CParameterPlugin'],['../classCParameterOperate.html#section_Use_CParameterPlugin',1,'Use CParameterPlugin']]],
  ['cparameterplugin_20for_20cparameteroperate_162',['Set CParameterPlugin for CParameterOperate',['../classCParameterOperate.html#sub_Set_CParameterPlugin_in_CParameterOperate',1,'']]],
  ['cparameterplugin_20in_20cparameteroperate_163',['Use CParameterPlugin in CParameterOperate',['../classCParameterOperate.html#sub_Use_CParameterPlugin_in_CParameterOperate',1,'']]],
  ['cparameterpluginui_164',['CParameterPluginUI',['../classCParameterPluginUI.html',1,'']]],
  ['cparameterproxy_165',['CParameterProxy',['../classCParameterProxy.html',1,'']]],
  ['cparameterproxyui_166',['CParameterProxyUI',['../classCParameterProxyUI.html',1,'']]],
  ['cparameterrawstream_167',['CParameterRawStream',['../classCParameterRawStream.html',1,'']]],
  ['cparameterrecord_168',['CParameterRecord',['../classCParameterRecord.html',1,'']]],
  ['cparameterrecordui_169',['CParameterRecordUI',['../classCParameterRecordUI.html',1,'']]],
  ['cparameterscreencapture_170',['CParameterScreenCapture',['../classCParameterScreenCapture.html',1,'']]],
  ['cparameterserialport_171',['CParameterSerialPort',['../classCParameterSerialPort.html',1,'']]],
  ['cparameterservice_172',['CParameterService',['../classCParameterService.html',1,'']]],
  ['cparameterservicefreerdp_173',['CParameterServiceFreeRDP',['../classCParameterServiceFreeRDP.html',1,'']]],
  ['cparameterservicelibvnc_174',['CParameterServiceLibVNC',['../classCParameterServiceLibVNC.html',1,'']]],
  ['cparameterservicerabbitvnc_175',['CParameterServiceRabbitVNC',['../classCParameterServiceRabbitVNC.html',1,'']]],
  ['cparameterservicetigervnc_176',['CParameterServiceTigerVNC',['../classCParameterServiceTigerVNC.html',1,'']]],
  ['cparameterssh_177',['CParameterSSH',['../classCParameterSSH.html',1,'']]],
  ['cparametersshtunnel_178',['CParameterSSHTunnel',['../classCParameterSSHTunnel.html',1,'']]],
  ['cparametersshtunnelui_179',['CParameterSSHTunnelUI',['../classCParameterSSHTunnelUI.html',1,'']]],
  ['cparametertelnet_180',['CParameterTelnet',['../classCParameterTelnet.html',1,'']]],
  ['cparameterterminal_181',['CParameterTerminal',['../classCParameterTerminal.html',1,'']]],
  ['cparameterterminalbase_182',['CParameterTerminalBase',['../classCParameterTerminalBase.html',1,'']]],
  ['cparameterterminalssh_183',['CParameterTerminalSSH',['../classCParameterTerminalSSH.html',1,'']]],
  ['cparameterterminalui_184',['CParameterTerminalUI',['../classCParameterTerminalUI.html',1,'']]],
  ['cparameterui_185',['CParameterUI',['../classCParameterUI.html',1,'']]],
  ['cparameteruser_186',['CParameterUser',['../classCParameterUser.html',1,'']]],
  ['cparameteruserui_187',['CParameterUserUI',['../classCParameterUserUI.html',1,'']]],
  ['cparametervnc_188',['CParameterVnc',['../classCParameterVnc.html',1,'']]],
  ['cparameterwakeonlan_189',['CParameterWakeOnLan',['../classCParameterWakeOnLan.html',1,'']]],
  ['cparameterwakeonlanui_190',['CParameterWakeOnLanUI',['../classCParameterWakeOnLanUI.html',1,'']]],
  ['cplugin_191',['CPlugin',['../classCPlugin.html',1,'']]],
  ['cpluginclientthread_192',['CPluginClientThread',['../classCPluginClientThread.html',1,'']]],
  ['cpluginfiletransfer_193',['CPluginFileTransfer',['../classCPluginFileTransfer.html',1,'']]],
  ['cpluginfreerdp_194',['cpluginfreerdp',['../classCPluginFreeRDP.html#a1a57743b0c84a7a4a8c0b97bd8954b66',1,'CPluginFreeRDP::CPluginFreeRDP()'],['../classCPluginFreeRDP.html',1,'CPluginFreeRDP']]],
  ['cpluginlibssh_195',['CPluginLibSSH',['../classCPluginLibSSH.html',1,'']]],
  ['cpluginlibvncserver_196',['CPluginLibVNCServer',['../classCPluginLibVNCServer.html',1,'']]],
  ['cpluginplayer_197',['CPluginPlayer',['../classCPluginPlayer.html',1,'']]],
  ['cpluginrabbitvnc_198',['cpluginrabbitvnc',['../classCPluginRabbitVNC.html',1,'CPluginRabbitVNC'],['../classCPluginRabbitVNC.html#a201b9a155d14bc33c60506e863805edc',1,'CPluginRabbitVNC::CPluginRabbitVNC()']]],
  ['cpluginrawstream_199',['CPluginRawStream',['../classCPluginRawStream.html',1,'']]],
  ['cpluginscreencapture_200',['CPluginScreenCapture',['../classCPluginScreenCapture.html',1,'']]],
  ['cpluginserialport_201',['CPluginSerialPort',['../classCPluginSerialPort.html',1,'']]],
  ['cpluginservice_202',['CPluginService',['../classCPluginService.html',1,'']]],
  ['cpluginservicefreerdp_203',['CPluginServiceFreeRDP',['../classCPluginServiceFreeRDP.html',1,'']]],
  ['cpluginservicelibvncserver_204',['CPluginServiceLibVNCServer',['../classCPluginServiceLibVNCServer.html',1,'']]],
  ['cpluginservicerabbitvnc_205',['CPluginServiceRabbitVNC',['../classCPluginServiceRabbitVNC.html',1,'']]],
  ['cpluginservicethread_206',['CPluginServiceThread',['../classCPluginServiceThread.html',1,'']]],
  ['cpluginservicetigervnc_207',['CPluginServiceTigerVNC',['../classCPluginServiceTigerVNC.html',1,'']]],
  ['cplugintelnet_208',['CPluginTelnet',['../classCPluginTelnet.html',1,'']]],
  ['cpluginterminal_209',['CPluginTerminal',['../classCPluginTerminal.html',1,'']]],
  ['cpluginthread_210',['CPluginThread',['../classCPluginThread.html',1,'']]],
  ['cplugintigervnc_211',['cplugintigervnc',['../classCPluginTigerVnc.html',1,'CPluginTigerVnc'],['../classCPluginTigerVnc.html#af179fdf68d4123ec6c2e20b9c0245360',1,'CPluginTigerVnc::CPluginTigerVnc()']]],
  ['cpluginwakeonlan_212',['CPluginWakeOnLan',['../classCPluginWakeOnLan.html',1,'']]],
  ['createoperate_213',['createoperate',['../classCPluginWakeOnLan.html#adbec5912e35b2a6c51473d9ecc9442e0',1,'CPluginWakeOnLan::CreateOperate()'],['../classCManager.html#a37bfb18878dd6fbdc05280a960912464',1,'CManager::CreateOperate()'],['../classCPlugin.html#ac8cec990249ce5b34f0d43148925079e',1,'CPlugin::CreateOperate()']]],
  ['creator。建议使用_20v5_200_202_20及以后版本，以前版本对_20cmake_20支持不够。_214',['[可选] IDE: Qt Creator。建议使用 v5.0.2 及以后版本，以前版本对 CMake 支持不够。',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md144',1,'']]],
  ['creator_215',['creator',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux__zh__CN.html#autotoc_md137',1,'Qt Creator'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Windows__zh__CN.html#autotoc_md194',1,'Qt Creator'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md99',1,'Qt Creator'],['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Android.html#autotoc_md87',1,'Qt Creator']]],
  ['creator_20it_20is_20recommended_20to_20use_20version_20v5_200_202_20or_20later_216',['[OPTIONAL] IDE: Qt Creator. It is recommended to use version v5.0.2 or later.',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Linux.html#autotoc_md106',1,'']]],
  ['crecordvideo_217',['CRecordVideo',['../classCRecordVideo.html',1,'']]],
  ['crecordvideothread_218',['crecordvideothread',['../classCRecordVideoThread.html',1,'CRecordVideoThread'],['../classCRecordVideoThread.html#a9459ef7a1c97e42bca113fd7ccead783',1,'CRecordVideoThread::CRecordVideoThread()']]],
  ['cremotefilesystem_219',['CRemoteFileSystem',['../classCRemoteFileSystem.html',1,'']]],
  ['cremotefilesystemmodel_220',['CRemoteFileSystemModel',['../classCRemoteFileSystemModel.html',1,'']]],
  ['cscreen_221',['CScreen',['../classCScreen.html',1,'']]],
  ['cscreencapture_222',['CScreenCapture',['../classCScreenCapture.html',1,'']]],
  ['cscreenwindows_223',['CScreenWindows',['../classCScreenWindows.html',1,'']]],
  ['cscreenxlib_224',['CScreenXLib',['../classCScreenXLib.html',1,'']]],
  ['cservice_225',['CService',['../classCService.html',1,'']]],
  ['cservicefreerdp_226',['CServiceFreeRDP',['../classCServiceFreeRDP.html',1,'']]],
  ['cservicelibvncserver_227',['CServiceLibVNCServer',['../classCServiceLibVNCServer.html',1,'']]],
  ['cservicemanager_228',['cservicemanager',['../classCServiceManager.html#a85f8b0f3a1297b9869cc221e297a7a4d',1,'CServiceManager::CServiceManager()'],['../classCServiceManager.html',1,'CServiceManager']]],
  ['cservicerabbitvnc_229',['CServiceRabbitVNC',['../classCServiceRabbitVNC.html',1,'']]],
  ['cservicethread_230',['CServiceThread',['../classCServiceThread.html',1,'']]],
  ['cservicetigervnc_231',['CServiceTigerVNC',['../classCServiceTigerVNC.html',1,'']]],
  ['csortip_232',['CSortIp',['../classCSortIp.html',1,'']]],
  ['csshtunnelthread_233',['CSSHTunnelThread',['../classCSSHTunnelThread.html',1,'']]],
  ['cstats_234',['CStats',['../classCStats.html',1,'']]],
  ['cterminal_235',['CTerminal',['../classCTerminal.html',1,'']]],
  ['cterminalparameter_236',['CTerminalParameter',['../classCTerminalParameter.html',1,'']]],
  ['currently_20supported_20on_20windows_237',['QTermWidget (Not currently supported on Windows)',['../md__2home_2runner_2work_2RabbitRemoteControl_2RabbitRemoteControl_2docs_2Compile_2Windows.html#autotoc_md186',1,'']]],
  ['cview_238',['CView',['../classCView.html',1,'']]],
  ['cviewsplitter_239',['CViewSplitter',['../classCViewSplitter.html',1,'']]],
  ['cviewsplittercontainer_240',['CViewSplitterContainer',['../classCViewSplitterContainer.html',1,'']]],
  ['cviewtable_241',['CViewTable',['../classCViewTable.html',1,'']]],
  ['cwakeonlan_242',['CWakeOnLan',['../classCWakeOnLan.html',1,'']]],
  ['cwakeonlanmodel_243',['CWakeOnLanModel',['../classCWakeOnLanModel.html',1,'']]],
  ['cwakeonlanqt_244',['CWakeOnLanQt',['../classCWakeOnLanQt.html',1,'']]]
];
